name: Build No Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os:
                - ubuntu-latest
                - macos-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch expanded history, which is needed for affected module detection
          fetch-depth: '500'
          lfs: 'true'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Check GIT lfs images
        run: |
          ./scripts/git-lfs-check.sh

      - name: Build (Debug)
        run: |
          ./gradlew --scan --stacktrace \
              assembleDebug